services:
  dtra_backend:
    build: .
    image: dtra-backend
    ports:
      - 8081:8081
    environment:
      DTRA_USER_USERNAME: ${DTRA_USER_USERNAME}
      DTRA_USER_PASSWORD: ${DTRA_USER_PASSWORD}
    depends_on:
      mongodb:
        condition: service_healthy
  mongodb:
    image: mongo:7.0
    container_name: dtra-mongodb
    ports:
      - "27017:27017"       
    volumes:
      - mongo-data:/data/db
      - type: bind
        source: ./mongo-entrypoint
        target: /docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME} 
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD} 
      MONGO_USER_USERNAME: ${DTRA_USER_USERNAME}
      MONGO_USER_PASSWORD: ${DTRA_USER_PASSWORD}
    healthcheck:
      test: echo 'db.runCommand({find:"dietotalerezepteapp.${MONGO_USER_USERNAME}"}).ok' | mongosh --authenticationDatabase admin --host localhost -u ${MONGO_INITDB_ROOT_USERNAME} -p ${MONGO_INITDB_ROOT_PASSWORD} admin --quiet | grep -q 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  mongo-data:
